### ISSUE TITLE
If there is a official latest installer for archlinux? It would be much appreciated.

### ISSUE THREAD

**Issue by yssource** [build2/build2-toolchain#1]
According to the INSTALL-GIT, I am trying to install it by `bash -xv ./build.sh --verbose 4 g++`
But, it always failed.

``` bash
trace: c::compile_rule::match: no C source file for target /home/jimmy/workspace/git/build2-toolchain/build2/build2/obje{b.?}
trace: cxx::compile_rule::apply: options mismatch forcing update of /home/jimmy/workspace/git/build2-toolchain/build2/build2/obje{b.o}
g++ -I/home/jimmy/workspace/git/build2-toolchain/libbutl -I/home/jimmy/workspace/git/build2-toolchain/libbutl -DLIBBUTL_SHARED -I/home/jimmy/workspace/git/build2-toolchain/libpkgconf -I/home/jimmy/workspace/git/build2-toolchain/build2 -I/home/jimmy/workspace/git/build2-toolchain/build2 -DBUILD2_HOST_TRIPLET="x86_64-linux-gnu" -std=c++2a -MQ ^ -x c++ -MD -E -fdirectives-only -MF /home/jimmy/workspace/git/build2-toolchain/build2/build2/b.o.t -o /home/jimmy/workspace/git/build2-toolchain/build2/build2/b.o.ii /home/jimmy/workspace/git/build2-toolchain/build2/build2/b.cxx
g++ -I/home/jimmy/workspace/git/build2-toolchain/libbutl -I/home/jimmy/workspace/git/build2-toolchain/libbutl -DLIBBUTL_SHARED -I/home/jimmy/workspace/git/build2-toolchain/libpkgconf -I/home/jimmy/workspace/git/build2-toolchain/build2 -I/home/jimmy/workspace/git/build2-toolchain/build2 -DBUILD2_HOST_TRIPLET="x86_64-linux-gnu" -std=c++2a -E -x c++ -fpreprocessed -fdirectives-only /home/jimmy/workspace/git/build2-toolchain/build2/build2/b.o.ii
trace: c::link_rule::match: non-C prerequisite /home/jimmy/workspace/git/build2-toolchain/build2/build2/:in/hxx{init.?} for target /home/jimmy/workspace/git/build2-toolchain/build2/build2/libue{b.u.a}
trace: search_existing_file: no existing file for prerequisite /home/jimmy/workspace/git/build2-toolchain/build2/doc/:man1{b.?}
trace: file_rule::match: no existing file for target /home/jimmy/workspace/git/build2-toolchain/build2/doc/man1{b.1}
error: no rule to update (for install) /home/jimmy/workspace/git/build2-toolchain/build2/doc/man1{b.1}
  info: while applying rule install.file to update (for install) /home/jimmy/workspace/git/build2-toolchain/build2/doc/man1{b.1}
  info: while applying rule install.alias to update (for install) /home/jimmy/workspace/git/build2-toolchain/build2/dir{doc/}
  info: while applying rule install.alias to update (for install) /home/jimmy/workspace/git/build2-toolchain/dir{build2/}
info: failed to update (for install) /home/jimmy/workspace/git/build2-toolchain/dir{build2/}
info: failed to update (for install) /home/jimmy/workspace/git/build2-toolchain/dir{bpkg/}
+ test 1 -ne 0
+ exit 1

```

- Linux jimmy-arch 4.19.16-1-MANJARO
- gcc (GCC) 8.2.1 20181127
- g++ (GCC) 8.2.1 20181127

As far as I know there is [build2-toolchain 0.6.2-1](https://aur.archlinux.org/packages/build2-toolchain/) , but it is out of date. 
Could you provide a official latest installer for archlinux? It would be much appreciated.

**Comment by boris-kolpackov** [comment]
Yes, building from a `git` clone is a bit broken for the time being (certain auto-generated files have to be generate manually). But we are making progress in fixing this eventually.

In the meantime, if you want to get the latest, the recommended way is to use the staged version. We stage pretty much daily so it track `master` very closely.

Now to the installer: the "official" installer for Arch Linux, as well as all other Linux'es is to use the install script as described in the Install page: https://build2.org/install.xhtml If you want to install the staged version, follow the same instructions but get the script from here: https://stage.build2.org/0/

Let us know how it goes!

**Comment by yssource** [comment]
Thanks a lot. I'v got so many helpful information from https://build2.org/

I have successfully installed it by script build2-install-0.8.0.sh.

Please feel free to close this issue, if the install-git works OK later.

By the way, It is possible to mirror other projects from cppget.org to github, isn't it?  Specially for the [cli](
https://git.codesynthesis.com/cgit/cli/cli/) , [odb](https://git.codesynthesis.com/cgit/odb/odb/)

**Comment by boris-kolpackov** [comment]
Setting up mirroring takes a bit of effort. But we are planning to mirror ODB, etc., at some point.
